### PR TITLE
Resolved issues with pyspark-cassandra packages and race condition errors

### LINKED ISSUE #36: Investigate solution for race condition in script submission
A report of the issue:

https://issues.apache.org/jira/browse/SPARK-10878
https://github.com/apache/spark/pull/9624#issuecomment-156922650

When scripts are submitted via spark-submit, it's possible that some may fails due to a non thread safe way Spark access some critical files.

Investigate this issue to find a workaround. Currently we avoid submitting analysers tasks in parallel, while data-transformer tasks on different topics are sent in parallel.

**Current solution:**

We currently avoid using `--packages` that was causing the race condition. We store the dependencies directly on Spark. This will change once we will move Spark outside and we will use it as a service.

### PR DESCRIPTION
**Pull request by Cerfoglg**
- Now using coroutines for parallel execution again
- Repeating scripts in case of runtime failure (fixes #36)
- Now using pyspark-cassandra from an assembly jar
- Added Spark configuration file for console logging (suppressing INFO
  messages)

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -46,6 +46,8 @@ RUN apk --update add curl tar python py-yaml && \
 COPY ./configuration /app/configuration
 # TODO: Remove this
 COPY ./conf /app/data-transformers/conf
+COPY ./dependencies/pyspark-cassandra-assembly-0.2.7.jar $SPARK_HOME/
+COPY ./configuration/log4j.properties $SPARK_HOME/conf/
```
Comment (VincenzoFerme) [inline Dockerfile]: This file is not committed

File: src/cloud/benchflow/sender/sender.go [hunk 2]
```diff
@@ -164,8 +169,8 @@ func consumeFromTopic(t TransformerSetting) {
 						Packages(s.Packages).
 						Script(s.Script).
 						//Files(s.Files).
-						//Files("/Users/Gabo/benchflow/spark-tasks-sender/conf/data-transformers/"+msg.SUT_name+".data-transformers.yml").
-						Files("/app/data-transformers/conf/data-transformers/"+msg.SUT_name+".data-transformers.yml").
+						Files("/Users/Gabo/benchflow/spark-tasks-sender/conf/data-transformers/"+msg.SUT_name+".data-transformers.yml").
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/sender/sender.go]: Hardcoding

File: src/cloud/benchflow/sender/sender.go [hunk 3]
```diff
@@ -73,10 +74,12 @@ type KafkaMessage struct {
 
 func constructTransformerSubmitCommand(ss SparkSubmit) exec.Cmd {
 	var args []string
-	args = append(args, "--master", ss.SparkMaster)
+	args = append(args, "--jars", sparkHome+"/pyspark-cassandra-assembly-0.2.7.jar")
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/sender/sender.go]: Use a shared variable to store the version (e.g., `pysparkCassandraVersion`) and refer to it.

File: src/cloud/benchflow/sender/sender.go [hunk 4]
```diff
@@ -177,14 +182,31 @@ func consumeFromTopic(t TransformerSetting) {
...
 						Build()
 					cmd := constructTransformerSubmitCommand(ss)
-					cmd.Stdout = os.Stdout
-    				cmd.Stderr = os.Stderr
-					err := cmd.Start()
-					cmd.Wait()
-					if err != nil {
-						panic(err)
+					retries := 0
+					for true {
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/sender/sender.go]: Use an actual for with the `retries` variable.

File: src/cloud/benchflow/sender/sender.go [hunk 5]
```diff
@@ -177,14 +182,31 @@ func consumeFromTopic(t TransformerSetting) {
...
+						//cmd.Stderr = os.Stderr
+						errOutput := &bytes.Buffer{}
+						cmd.Stderr = errOutput
+						err := cmd.Start()
+						cmd.Wait()
+						if err != nil {
+							panic(err)
+							}
+						errLog := errOutput.String()
+						if checkForErrors(errLog) {
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/sender/sender.go]: Use an `if...else`

File: src/cloud/benchflow/sender/sender.go [hunk 6]
```diff
@@ -196,23 +218,43 @@ func consumeFromTopic(t TransformerSetting) {
 
 func submitAnalyser(script string, trialID string, minioKey string) {
 	var args []string
+	args = append(args, "--jars", sparkHome+"/pyspark-cassandra-assembly-0.2.7.jar")
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/sender/sender.go]: Use a shared variable to store the version (e.g., `pysparkCassandraVersion`) and refer to it.

File: src/cloud/benchflow/sender/sender.go [hunk 7]
```diff
@@ -196,23 +218,43 @@ func consumeFromTopic(t TransformerSetting) {
...
 	fmt.Println(args)
+	retries := 0
 	cmd := exec.Command(sparkHome+"/bin/spark-submit", args...)
-	cmd.Stdout = os.Stdout
-	cmd.Stderr = os.Stderr
-	err := cmd.Start()
-	cmd.Wait()
-	if err != nil {
-		panic(err)
+	for true {
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/sender/sender.go]: The same as the previous `for true`. Moreover, since you have this code twice, I would use a function.
