### PR TITLE
Fix for configuration path

### LINKED ISSUE #86: Mysql Transformer Error In Retrieving Configuration File
An execution log reporting the error as in the title. Moreover in case of an error, the computation must not be marked as succeeded as it seems to be marked from the following logs.

```
8/21/2016 6:11:18 PMReceived message: {"minio_key":"eaa2/BenchFlow.wfmsTest.1.1/BenchFlow.wfmsTest.1.1.1/benchflow.collector.mysql.db_BenchFlow.wfmsTest.1.1.1/mysql/mysql/process-engine","trial_id":"BenchFlow.wfmsTest.1.1.1","experiment_id":"BenchFlow.wfmsTest.1.1","container_id":"mysql","container_name":"mysql","host_id":"host","collector_name":"mysql"}
8/21/2016 6:11:18 PMmysql topic, submitting script data-transformers/transformers/mysqlTransformer.py, minio location: eaa2/BenchFlow.wfmsTest.1.1/BenchFlow.wfmsTest.1.1.1/benchflow.collector.mysql.db_BenchFlow.wfmsTest.1.1.1/mysql/mysql/process-engine, trial id: BenchFlow.wfmsTest.1.1.1
8/21/2016 6:11:18 PMTransformer work request queued for script mysql, camunda, 7.5.0, BenchFlow.wfmsTest.1.1.1, mysql, host, trial
8/21/2016 6:11:18 PMReceived work request for script mysql, camunda, 7.5.0, BenchFlow.wfmsTest.1.1.1, mysql, host, trial
8/21/2016 6:11:18 PMDispatching work request for script mysql, camunda, 7.5.0, BenchFlow.wfmsTest.1.1.1, mysql, host, trial
8/21/2016 6:11:18 PMTransformer worker submitting script:  [--master local[*] --jars /usr/spark/pyspark-cassandra-assembly-0.3.5.jar --driver-memory 12g --executor-memory 12g --conf spark.executor.heartbeatInterval=300000s --conf spark.storage.blockManagerSlaveTimeoutMs=300000s --conf spark.core.connection.ack.wait.timeout=300000s --conf spark.cassandra.connection.host=cassandra --driver-class-path /usr/spark/pyspark-cassandra-assembly-0.3.5.jar --py-files /app/data-transformers/commons/commons.py,/app/data-transformers/transformations/dataTransformations.py,/usr/spark/pyspark-cassandra-assembly-0.3.5.jar /app/data-transformers/transformers/mysqlTransformer.py {"cassandra_keyspace":"benchflow","minio_host":"minio","minio_port":"9000","minio_access_key":"CYNQML6R7V12MTT32W6P","minio_secret_key":"SQ96V5pg02Z3kZ/0ViF9YY6GwWzZvoBmElpzEEjn","file_bucket":"runs","file_path":"eaa2/BenchFlow.wfmsTest.1.1/BenchFlow.wfmsTest.1.1.1/benchflow.collector.mysql.db_BenchFlow.wfmsTest.1.1.1/mysql/mysql/process-engine","trial_id":"BenchFlow.wfmsTest.1.1.1","experiment_id":"BenchFlow.wfmsTest.1.1","config_file":"data-transformers.configuration.yml","container_id":"mysql","host_id":"host"}]
8/21/2016 6:11:18 PM/apps/bin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin
8/21/2016 6:11:22 PMTraceback (most recent call last):
8/21/2016 6:11:22 PM  File "/app/data-transformers/transformers/mysqlTransformer.py", line 196, in <module>
8/21/2016 6:11:22 PM    main()
8/21/2016 6:11:22 PM  File "/app/data-transformers/transformers/mysqlTransformer.py", line 140, in main
8/21/2016 6:11:22 PM    with open(confPath) as f:
8/21/2016 6:11:22 PMIOError: [Errno 2] No such file or directory: u'/tmp/spark-1f5c7d2d-5bd1-4645-accf-6511a3dddd34/userFiles-47d4f8d2-27ee-4f7e-88d5-66cd1f15a41f/data-transformers.configuration.yml'
8/21/2016 6:11:22 PM
8/21/2016 6:11:22 PMScript data-transformers/transformers/mysqlTransformer.py processed
8/21/2016 6:11:22 PMTransformer script completed successfully: mysql, camunda, 7.5.0, BenchFlow.wfmsTest.1.1.1, mysql, host, trial
8/21/2016 6:11:22 PMAll requirements met for: mysql
```

Please test also all the other transformers again in the current state of the system. And add test cases for all the encountered problems.

### PR DESCRIPTION
**Pull request by Cerfoglg**
Fixes https://github.com/benchflow/data-transformers/issues/86

The fix assumes that all the folders and files in the plugin repo are lowercase. That is fine for now, for the sake of traceability, I took a note in benchflow/sut-plugins#4
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75599409%22%2C%20%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75599464%22%2C%20%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75599967%22%2C%20%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75600005%22%2C%20%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75600007%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20b6a667f74e728c95caef913af3527b7f4f6c456a%20src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go%204%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75599409%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Does%20this%20belong%20to%20the%20current%20pull%3F%20I%20guess%20it%20does%20not%2C%20it%20is%20more%20related%20to%20https%3A//github.com/benchflow/data-analyses-scheduler/issues/82.%20Roll%20back%20the%20change%20and%20perform%20it%20in%20a%20different%20pull.%22%2C%20%22created_at%22%3A%20%222016-08-21T17%3A27%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20Okay%22%2C%20%22created_at%22%3A%20%222016-08-21T17%3A49%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-none%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222016-08-21T17%3A52%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go%3AL73-82%22%7D%2C%20%22Pull%20b6a667f74e728c95caef913af3527b7f4f6c456a%20src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go%204%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/data-analyses-scheduler/pull/83%23discussion_r75599464%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20assumes%20that%20all%20the%20folders%20and%20files%20in%20the%20plugin%20repo%20are%20lowercase.%20That%20is%20fine%20for%20now%2C%20for%20the%20sake%20of%20traceability%2C%20I%20took%20a%20note%20in%20https%3A//github.com/benchflow/sut-plugins/issues/4%22%2C%20%22created_at%22%3A%20%222016-08-21T17%3A29%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%3Ca%20href%3D%27%23crh-update-complete%27%3E%3C/a%3E%22%2C%20%22created_at%22%3A%20%222016-08-21T17%3A52%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go%3AL11-19%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-Pull b6a667f74e728c95caef913af3527b7f4f6c456a src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go 4'></a> &nbsp;<b><a href='https://github.com/benchflow/data-analyses-scheduler/pull/83#discussion_r75599409'>File: src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go:L73-82</a></b>
- <a href='https://github.com/VincenzoFerme'></a> Does this belong to the current pull? I guess it does not, it is more related to https://github.com/benchflow/data-analyses-scheduler/issues/82. Roll back the change and perform it in a different pull.
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme Okay
- [x] <a href='#crh-comment-Pull b6a667f74e728c95caef913af3527b7f4f6c456a src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go 4'></a> &nbsp;<b><a href='https://github.com/benchflow/data-analyses-scheduler/pull/83#discussion_r75599464'>File: src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go:L11-19</a></b>
- <a href='https://github.com/VincenzoFerme'></a> This assumes that all the folders and files in the plugin repo are lowercase. That is fine for now, for the sake of traceability, I took a note in https://github.com/benchflow/sut-plugins/issues/4

<a href='https://www.codereviewhub.com/benchflow/data-analyses-scheduler/pull/83?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/data-analyses-scheduler/pull/83?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/data-analyses-scheduler/pull/83'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/data-analyses-scheduler/pull/83'>Refresh</a>.<a href='#crh-update-none'></a>

File: src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go [hunk 1]
```diff
@@ -73,5 +73,9 @@ func checkForErrors(errLog string) bool {
 	if strings.Contains(errString, "exception") {
 		return true
 		}
+	//TODO: Find a better way to identify error tracebacks
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go]: Does this belong to the current pull? I guess it does not, it is more related to https://github.com/benchflow/data-analyses-scheduler/issues/82. Roll back the change and perform it in a different pull.

File: src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go [hunk 2]
```diff
@@ -11,6 +11,8 @@ import (
 func getConfigFilePath(SUTVersion string, SUTName string, SUTType string, fileName string) string {
 	// Split the version into 3 numbers (eg. 1.0.2 -> [1 0 2])
 	versionNums := strings.Split(SUTVersion, ".")
+	SUTName = strings.ToLower(SUTName)
```
Comment (VincenzoFerme) [inline src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go:14]: This assumes that all the folders and files in the plugin repo are lowercase. That is fine for now, for the sake of traceability, I took a note in https://github.com/benchflow/sut-plugins/issues/4

File: src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go (hunk 1 above)
Comment (Cerfoglg) [inline src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go]: @VincenzoFerme Okay

Comment (VincenzoFerme) [inline src/cloud/benchflow/data-analyses-scheduler/scripts/scriptSubmission.go]: :+1:<a href='#crh-update-none'></a>

File: src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go (hunk 2 above)
Comment (VincenzoFerme) [inline src/cloud/benchflow/data-analyses-scheduler/scripts/sparkArgsConstructors.go:14]: :+1:<a href='#crh-update-complete'></a>
